"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@ant-design/v5-patch-for-react-19";
import { Layout } from "antd";
import React from "react";
import Login from "./login/Login.tsx";
const { Header, Sider, Content, Footer } = Layout;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout style={{ minHeight: "100vh" }}>
          <Header>
            <Login />
          </Header>

          <Layout>
            <Sider width={200} style={{ background: "#fff" }}>
              {/* 左侧菜单内容 */}
              <p>Sider</p>
            </Sider>

            <Content style={{ margin: "24px 16px 0" }}>
              {/* 主体内容区域 */}
              <div style={{ padding: 24, background: "#fff", minHeight: 360 }}>
                {children}
              </div>
            </Content>
          </Layout>

          <Footer style={{ textAlign: "center" }}>
            {/* 底部内容 */}
            <p>Footer</p>
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
