spring:
  profiles:
    active:
    - oa
    - oa
  application: 
    name: oa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
      
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc: 
          batch_size: 100
          order_inserts: true
          order_updates: true
          return-first-only: false
        enhancer:
          enableLazyInitialization: true
          enableAssociationManagement: true
          enableDirtyTracking: true
  jackson: 
    default-property-inclusion: NON_NULL

  threads:
    virtual:
      enabled: true  
logging:
  level:
    root: info
    com.zaxxer.hikari.pool: info
    org.camunda.bpm.engine: info
    javax.management: info
    sun.rmi: info
    org.postgresql.jdbc: info
    org.springframework.orm: info
    org.springframework.data: info
    io.lettuce: info
    org.springframework.security.web: info
  file: 
    path: /home/sunft/oa/logs/
    name: /home/sunft/oa/logs/oa.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss,Asia/Shanghai,zh-CN
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai,zh-CN} %-5level [%-15.15(%thread)] %-50.50(%logger{50}) : %msg%n" 
    
management: 
  endpoints:
    web: 
      exposure:
        include: 
         - beans
app: 
  base-url: http://10.0.0.130:4000
  data-table-nums: 5
camunda:
  bpm:
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false

