package io.github.benxincaomu.oa.bussiness.workflow;

import java.text.MessageFormat;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeUnit;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.core.simple.JdbcClient.MappedQuerySpec;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.Resource;
import jakarta.transaction.Transactional;

/**
 * 流程数据表服务
 */
@Service
public class DataTableService {

    @Resource
    private JdbcClient jdbcClient;

    @Resource
    private RedisTemplate<String, String> redisTemplate;

    private final Logger logger = LoggerFactory.getLogger(DataTableService.class);

    @Value("${app.data-table-nums:5}")
    private Integer dataTableNums;

    private ThreadLocal<Integer> dataTableIndexLocal = new ThreadLocal<>();

    private final String[] flowFormDdls = {
            """
                            CREATE TABLE public.{0} (
                    	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                    	create_at timestamp(6) NULL,
                    	create_by int8 NULL,
                    	tenant_id int8 NULL,
                    	update_at timestamp(6) NULL,
                    	update_by int8 NULL,
                    	"data" jsonb NULL,
                    	publish_id int8 NULL,
                        deploy_name varchar(36) NULL,
                     process_id varchar(36) NULL,
                    	CONSTRAINT {1}_pkey PRIMARY KEY (id)
                    );

                                    """,
            "CREATE INDEX {0}_create_by_index ON public.{1} USING btree (create_by)",
            "CREATE INDEX {0}_publish_id_index ON public.{1} USING btree (publish_id);"
    };

    private final String[] flowHistoryDdls = {

            """
                                CREATE TABLE public.{0} (
                    	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                    	create_at timestamp(6) NULL,
                    	create_by int8 NULL,
                    	tenant_id int8 NULL,
                    	update_at timestamp(6) NULL,
                    	update_by int8 NULL,
                    	approval_opinion varchar(200) NULL,
                    	flow_form_id int8 NULL,
                    	flow_name varchar(255) NULL,
                        operator_name varchar(20) NULL,
                        flow_id varchar(50) NULL,
                    	CONSTRAINT {1}_pkey PRIMARY KEY (id)
                    )

                                        """,
            "CREATE INDEX {0}_id_index ON public.{1} USING btree (flow_form_id)"
    };

    private final String flowFormTableNamePrefix = "flow_form_table_";

    private final String flowHistoryTableNamePrefix = "flow_history_table_";

    /**
     * 初始化数据表和历史表
     */
    @PostConstruct
    @Transactional
    public void initTables() {
        MappedQuerySpec<String> query = jdbcClient
                .sql("SELECT tablename FROM pg_tables WHERE schemaname = 'public' and tablename like concat(?::text,'%')")
                .param(flowFormTableNamePrefix)
                .query(String.class);
        int tableNums = query.list().size();

        String lockKey = "initDataTableLock";
        if (tableNums < dataTableNums && Objects
                .equals(redisTemplate.opsForValue().setIfAbsent(lockKey, "1", 30L, TimeUnit.SECONDS), Boolean.TRUE)) {

            int tablesToCreate = dataTableNums - tableNums;
            logger.info("当前表数量:{}", tableNums);
            logger.info("需创建表数量:{}", tablesToCreate);
            for (int i = dataTableNums - 1; i >= tableNums; i--) {
                String flowTableName = flowFormTableNamePrefix + i;
                logger.info("创建表:{}", flowTableName);
                for (String ddl : flowFormDdls) {

                    jdbcClient.sql(MessageFormat.format(ddl, flowTableName, flowTableName)).update();
                }
                String flowHistoryTableName = flowHistoryTableNamePrefix + i;

                for (String ddl : flowHistoryDdls) {
                    jdbcClient.sql(MessageFormat.format(ddl, flowHistoryTableName, flowHistoryTableName)).update();
                }
                logger.info("已完成创建表:{}", flowTableName);
            }
        }
    }

    /**
     * 选择数据表
     * 一定要先选数据表，后选历史表
     * 
     * @return
     */
    public String selectFormTable() {
        MappedQuerySpec<String> query = jdbcClient
                .sql("SELECT tablename FROM pg_tables WHERE schemaname = 'public' and tablename like concat(?::text,'%')")
                .param(flowFormTableNamePrefix)
                .query(String.class);
        List<String> tableNames = query.list();
        if (tableNames.size() > 0) {
            String selectedTableName = tableNames.get(0);
            int minDataCount = 0;
            int selectedTableIndex = 0;
            for (int i = 0; i < tableNames.size(); i++) {
                Integer count = jdbcClient.sql("select count(id) from " + tableNames.get(i)).query(Integer.class)
                        .single();

                if (count < minDataCount) {
                    minDataCount = count;
                    selectedTableName = tableNames.get(i);
                    selectedTableIndex = i;
                }
            }
            dataTableIndexLocal.set(selectedTableIndex);
            return selectedTableName;
        }
        return "";
    }

    /**
     * 选择历史表
     * 
     * @return
     */
    public String selectHistoryTable() {
        Integer index = dataTableIndexLocal.get();
        if (index == null) {
            throw new IllegalStateException("请先选择数据表");
        }
        dataTableIndexLocal.remove();
        return flowHistoryTableNamePrefix + index;
    }

}
